#!/bin/sh

src=$1
dst=${src/python-/python27-}

yumdownloader --disablerepo rpmfusion\* --source $src
rpmdev-extract $src*.rpm
rm $src*.rpm
mv $src*.src $dst
mv $dst/$src.spec $dst/$dst.spec
sed \
	-e 's/^\([A-Z][a-zA-Z0-9]\+:\)[\t ]\+/\1 /' \
	-e '/^Name:/s/python-/python27-/' \
	-i $dst/$dst.spec
echo include ../Makefile.base >$dst/Makefile
